language: java
jdk:
- oraclejdk8
cache:
  directories:
  - ".autoconf" 
  - "$HOME/.m2" 
before_install: mvn install:install-file -Dfile=./lib/classes12.jar -DgroupId=com.oracle
  -DartifactId=classes12 -Dversion=10.2.0.3 -Dpackaging=jar
